groups:
  - name: node_alerts
    rules:
      - alert: HighDiskUsage
        expr: ((node_filesystem_size_bytes{fstype=~"xfs|ext4"} - node_filesystem_free_bytes{fstype=~"xfs|ext4"} )/ node_filesystem_size_bytes{fstype=~"xfs|ext4"}) * 100 > 80
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Disk usage high: {{ $labels.instance }} - {{ $labels.mountpoint }}"
          description: 'Disk usage is at {{ $value | printf "%.2f" }}%'

      - alert: HighCPUUsage
        expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "CPU usage high"
          description: 'CPU usage is at {{ $value | printf "%.2f" }}%'

      - alert: HighMemoryUsage
        expr: ((node_memory_MemTotal_bytes{} - node_memory_MemAvailable_bytes{}) / node_memory_MemTotal_bytes) * 100 > 80
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Memory usage high"
          description: 'Memory usage is at {{ $value | printf "%.2f" }}%'

      - alert: NodeDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Node is down"
          description: "Node {{ $labels.instance }} is down"